# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q3C9A4Zfew3spIaAZZg7xJDMudhSl954
"""

import gradio as gr
import anthropic
import json
from typing import List, Dict

# ============================================
# 🔑 PUT YOUR API KEY HERE
# ============================================
ANTHROPIC_API_KEY = "s-key"  # ← REPLACE THIS WITH YOUR ACTUAL KEY
# ============================================

# Knowledge base of TikTok best practices
KNOWLEDGE_BASE = [
    {
        "id": 1,
        "category": "hooks",
        "content": "Start with the outcome first - show what viewers will learn or achieve in the first 2 seconds. Example: 'This trick got me 10k followers' instead of 'Today I'll show you...'"
    },
    {
        "id": 2,
        "category": "hooks",
        "content": "Use pattern interrupts - unexpected sounds, visual glitches, or questions that make viewers stop scrolling. Example: 'Wait, don't scroll' or record scratch sound effect."
    },
    {
        "id": 3,
        "category": "hooks",
        "content": "Lead with a strong question that creates curiosity gap. Example: 'Why does nobody talk about this?' or 'Did you know this actually works?'"
    },
    {
        "id": 4,
        "category": "retention",
        "content": "Keep every frame valuable - aim for no more than 2-3 seconds per idea. Cut any dead space. If you're not adding value, viewers leave."
    },
    {
        "id": 5,
        "category": "retention",
        "content": "Use text overlays to reinforce your message - 70% of TikTok is watched without sound. Key points should be readable on screen."
    },
    {
        "id": 6,
        "category": "retention",
        "content": "Create a loop structure where the end connects to the beginning. This increases rewatches, which TikTok loves."
    },
    {
        "id": 7,
        "category": "editing",
        "content": "Use trending sounds strategically - but make sure they fit your content naturally. Forced trends hurt authenticity."
    },
    {
        "id": 8,
        "category": "editing",
        "content": "Jump cuts every 2-3 seconds maintain energy. Static shots lose attention quickly in short-form."
    },
    {
        "id": 9,
        "category": "editing",
        "content": "Zoom in on key moments for emphasis. Quick zooms = emphasis, slow zooms = dramatic reveal."
    },
    {
        "id": 10,
        "category": "captions",
        "content": "First line of caption should expand on your hook, not repeat it. Add value immediately."
    },
    {
        "id": 11,
        "category": "captions",
        "content": "Include 3-5 relevant hashtags mixing popular (#fyp) and niche tags specific to your content."
    },
    {
        "id": 12,
        "category": "captions",
        "content": "End captions with a question or call-to-action to boost comments. Example: 'What would you try first?'"
    },
    {
        "id": 13,
        "category": "study-with-me",
        "content": "Study-with-me videos perform well with cozy aesthetics - warm lighting, organized desk setup, soft background music."
    },
    {
        "id": 14,
        "category": "study-with-me",
        "content": "Show productivity systems - Pomodoro timers, task lists being checked off. Viewers love tangible progress."
    },
    {
        "id": 15,
        "category": "fitness",
        "content": "Fitness content: show the transformation/result in first frame, then the method. 'This is how I did it' format works."
    },
    {
        "id": 16,
        "category": "fitness",
        "content": "Demonstrate exercises with split screen showing common mistakes vs correct form. Educational + engaging."
    },
    {
        "id": 17,
        "category": "booktok",
        "content": "BookTok: Create tension with emotional reactions - crying, gasping, throwing the book. Viewers want to know WHY."
    },
    {
        "id": 18,
        "category": "booktok",
        "content": "Use dramatic reenactments of book scenes with text overlay of the actual quote. Makes static content dynamic."
    },
    {
        "id": 19,
        "category": "general",
        "content": "Post consistently at your audience's peak times. Use TikTok analytics to find when your followers are most active."
    },
    {
        "id": 20,
        "category": "general",
        "content": "Respond to comments with video replies - this creates more content and shows you value your community."
    }
]


def retrieve_relevant_tips(query: str, top_k: int = 6) -> List[Dict]:
    """
    Simple keyword-based retrieval (RAG retrieval step)
    In production, this would use embeddings + vector search
    """
    query_lower = query.lower()
    keywords = query_lower.split()

    # Score each knowledge base item
    scored_items = []
    for item in KNOWLEDGE_BASE:
        score = 0
        content_lower = item["content"].lower()
        category_lower = item["category"].lower()

        # Check for keyword matches in content
        for keyword in keywords:
            if keyword in content_lower:
                score += 2
            if keyword in category_lower:
                score += 3

        scored_items.append({**item, "score": score})

    # Sort by score and return top_k
    scored_items.sort(key=lambda x: x["score"], reverse=True)
    relevant = [item for item in scored_items if item["score"] > 0][:top_k]

    # If no relevant tips found, return general tips
    if not relevant:
        relevant = [item for item in KNOWLEDGE_BASE
                   if item["category"] in ["general", "hooks"]][:top_k]

    return relevant


def generate_ideas(niche: str, goals: str = "") -> str:
    """
    Generate video ideas using RAG + Claude API
    """
    if not niche.strip():
        return "⚠️ Please describe your niche first!"

    try:
        # Step 1: Retrieve relevant tips (RAG retrieval)
        relevant_tips = retrieve_relevant_tips(f"{niche} {goals}")
        tips_context = "\n".join([f"- {tip['content']}" for tip in relevant_tips])

        # Step 2: Generate ideas with Claude (RAG generation)
        client = anthropic.Anthropic(
            api_key=ANTHROPIC_API_KEY
        )

        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1000,
            messages=[{
                "role": "user",
                "content": f"""You are a TikTok content strategist helping a creator generate video ideas.\n\nCreator's niche: {niche}\nCreator's goals: {goals or 'Create engaging content'}\n\nRelevant TikTok Best Practices:\n{tips_context}\n\nBased on these best practices and the creator's niche, generate exactly 3 video ideas. For each idea provide:\n1. A catchy video concept (one sentence)\n2. A powerful hook (the first line/visual - max 10 words)\n3. A caption with 3-5 hashtags\n\nFormat your response as JSON:\n{{\n  "ideas": [\n    {{\n      "concept": "video concept here",\n      "hook": "opening hook here",\n      "caption": "caption with hashtags here"\n    }}\n  ]\n}}\n\nMake the ideas specific, actionable, and optimized for TikTok's algorithm."""
            }]
        )

        # Parse response
        response_text = message.content[0].text

        # Extract JSON from response
        start_idx = response_text.find('{')
        end_idx = response_text.rfind('}') + 1
        json_str = response_text[start_idx:end_idx]

        parsed = json.loads(json_str)
        ideas = parsed["ideas"]

        # Format output beautifully
        output = "# 🎬 Your Video Ideas\n\n"

        for i, idea in enumerate(ideas, 1):
            output += f"## Video {i}\n\n"
            output += f"**Concept:** {idea['concept']}\n\n"
            output += f"**Hook:** *\"{idea['hook']}\"*\n\n"
            output += f"**Caption:**\n{idea['caption']}\n\n"
            output += "---\n\n"

        output += "### 📊 RAG Insights\n"
        output += f"Generated using {len(relevant_tips)} TikTok best practices:\n\n"
        for tip in relevant_tips[:3]:
            output += f"• **{tip['category'].upper()}**: {tip['content'][:100]}...\n"

        return output

    except Exception as e:
        return f"❌ Error: {str(e)}\n\nMake sure you replaced 'sk-ant-your-api-key-here' with your actual API key at the top of the script!"


# Custom CSS for TikTok dark theme
custom_css = """
/* Main container - TikTok black background */
.gradio-container {
    background-color: #000000 !important;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Proxima Nova', sans-serif !important;
}

/* All text white by default */
body, .gradio-container, .contain, .wrap {
    background-color: #000000 !important;
    color: #FFFFFF !important;
}

/* Header styling */
.markdown-text h1 {
    color: #FFFFFF !important;
    font-weight: 700 !important;
    font-size: 32px !important;
    margin-bottom: 8px !important;
}

.markdown-text h3 {
    color: #25F4EE !important;
    font-weight: 600 !important;
    font-size: 16px !important;
    margin-top: 0 !important;
}

.markdown-text p {
    color: #A0A0A0 !important;
    font-size: 14px !important;
}

/* Input fields - dark with cyan border on focus */
.input-text textarea,
input[type="text"],
textarea {
    background-color: #1A1A1A !important;
    border: 1px solid #333333 !important;
    color: #FFFFFF !important;
    border-radius: 8px !important;
    font-size: 15px !important;
    padding: 12px !important;
}

.input-text textarea:focus,
input[type="text"]:focus,
textarea:focus {
    border-color: #25F4EE !important;
    box-shadow: 0 0 0 2px rgba(37, 244, 238, 0.2) !important;
    outline: none !important;
}

.input-text textarea::placeholder,
input::placeholder,
textarea::placeholder {
    color: #666666 !important;
}

/* Labels */
label, .label {
    color: #FFFFFF !important;
    font-weight: 600 !important;
    font-size: 14px !important;
    margin-bottom: 8px !important;
}

/* Generate button - TikTok red/cyan style */
#generate_btn {
    background: linear-gradient(135deg, #FE2C55 0%, #25F4EE 100%) !important;
    border: none !important;
    color: #FFFFFF !important;
    font-weight: 700 !important;
    font-size: 16px !important;
    padding: 16px 32px !important;
    border-radius: 8px !important;
    text-transform: uppercase !important;
    letter-spacing: 1px !important;
    cursor: pointer !important;
    transition: all 0.3s ease !important;
}

#generate_btn:hover {
    transform: scale(1.02) !important;
    box-shadow: 0 8px 24px rgba(254, 44, 85, 0.4) !important;
}

/* Output section */
#output {
    background-color: #1A1A1A !important;
    border: 1px solid #333333 !important;
    border-radius: 12px !important;
    padding: 24px !important;
    color: #FFFFFF !important;
}

#output h1, #output h2, #output h3 {
    color: #FFFFFF !important;
}

#output h2 {
    color: #25F4EE !important;
    border-bottom: 1px solid #333333 !important;
    padding-bottom: 8px !important;
    margin-top: 20px !important;
}

#output p, #output li {
    color: #E0E0E0 !important;
    line-height: 1.6 !important;
}

#output strong {
    color: #25F4EE !important;
}

#output em {
    color: #FE2C55 !important;
}

#output hr {
    border-color: #333333 !important;
    margin: 24px 0 !important;
}

/* Examples section */
.examples {
    background-color: #1A1A1A !important;
    border: 1px solid #333333 !important;
    border-radius: 8px !important;
    padding: 16px !important;
}

.example {
    background-color: #0A0A0A !important;
    border: 1px solid #333333 !important;
    color: #FFFFFF !important;
    border-radius: 6px !important;
    padding: 8px 12px !important;
}

.example:hover {
    border-color: #25F4EE !important;
    background-color: #1A1A1A !important;
}

/* Info section */
#info {
    background-color: #0A0A0A !important;
    border-left: 3px solid #25F4EE !important;
    padding: 16px !important;
    margin-top: 24px !important;
    border-radius: 4px !important;
}

#info h3 {
    color: #25F4EE !important;
    margin-top: 0 !important;
}

#info p, #info li {
    color: #A0A0A0 !important;
}

/* Scrollbar */
::-webkit-scrollbar {
    width: 8px;
    background-color: #000000;
}

::-webkit-scrollbar-track {
    background-color: #1A1A1A;
}

::-webkit-scrollbar-thumb {
    background-color: #333333;
    border-radius: 4px;
}

::-webkit-scrollbar-thumb:hover {
    background-color: #25F4EE;
}

/* Remove any white backgrounds */
.contain, .wrap, .block, .panel {
    background-color: transparent !important;
}

/* Column styling */
.column {
    background-color: transparent !important;
}
"""

# Build Gradio Interface
with gr.Blocks(css=custom_css, title="TikTok Creator Copilot", theme=gr.themes.Base()) as demo:
    gr.Markdown(
        """
        # 🎵 TikTok Creator Copilot
        ### AI-powered idea generation using RAG architecture

        Generate viral video ideas with hooks and captions optimized for TikTok
        """,
        elem_id="header"
    )

    with gr.Row():
        with gr.Column(scale=1):
            niche_input = gr.Textbox(
                label="Your Niche",
                placeholder="study-with-me, fitness, book reviews, cooking...",
                lines=2,
                elem_classes="input-text"
            )

            goals_input = gr.Textbox(
                label="Your Goals (Optional)",
                placeholder="increase engagement, grow followers, go viral...",
                lines=2,
                elem_classes="input-text"
            )

            generate_btn = gr.Button(
                "Generate Ideas",
                variant="primary",
                elem_id="generate_btn",
                size="lg"
            )

    with gr.Row():
        output = gr.Markdown(
            label="Your Ideas",
            elem_id="output"
        )

    # Examples
    gr.Examples(
        examples=[
            ["study-with-me videos", "help students stay motivated"],
            ["fitness transformation", "inspire people to workout"],
            ["book reviews", "grow BookTok audience"],
            ["quick healthy meals", "teach busy professionals"],
            ["tech tips", "help people use devices"]
        ],
        inputs=[niche_input, goals_input],
        label="Quick Start Examples"
    )

    # Info section
    gr.Markdown(
        """
        ---
        ### 🔍 How RAG Works

        1. **Retrieval** → Searches 20+ TikTok best practices for your niche
        2. **Augmentation** → Adds relevant tips as context to AI prompt
        3. **Generation** → Claude creates personalized ideas using best practices

        **Knowledge Base:** Hooks • Retention • Editing • Captions • Niche Tips
        """,
        elem_id="info"
    )

    # Connect button to function
    generate_btn.click(
        fn=generate_ideas,
        inputs=[niche_input, goals_input],
        outputs=output
    )

# Launch the app
if __name__ == "__main__":
    print("🚀 Starting TikTok Creator Copilot...")
    print("🔑 Make sure you've set your ANTHROPIC_API_KEY at the top of this file!")
    print("💡 Get your key at: https://console.anthropic.com/settings/keys")
    demo.launch(
        share=True,  # Creates a public link
        server_name="0.0.0.0"
    )

!pip install anthropic
